services:

  database:
    build: "database"
    environment:
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - database

  simple-api:
    build: "simple-api"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=pwd
    networks:
      app-network:
        aliases:
          - simple-api

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  my-network:

volumes:
  db-volume :