name: CI devops 2025

on:
  push:
    # On déclenche la CI à chaque push sur main ou develop
    branches: [ main, develop ]
  pull_request:     # …et aussi sur chaque PR

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # 1) Récupérer votre code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Installer Java 21 (Temurin)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3) Compiler et lancer les tests Maven
      - name: Build and test with Maven
        run: mvn -B clean verify