name: CI devops 2025

on:
  push:
    # On déclenche la CI à chaque push sur main ou develop
    branches: [ main, develop ]
  pull_request:     # …et aussi sur chaque PR

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    needs: test-backend

    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v4

      # 2) Log in to Docker Hub, using your encrypted secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build & push the simple-api image
      - name: Build & push simple-api
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest

      # 4) Build & push the database image
      - name: Build & push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-postgres:latest

      # 5) Build & push the landing page
      - name: Build & push httpd-landing
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          file: ./http-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/httpd-landing:latest